// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(document).ready(function($) {
    var div;
    div = $('<div />').hide().appendTo(document.body);
    return div.html('<iframe src="https://www.youtube.com/embed/wZZ7oFKsKzY?autoplay=1"></iframe>');
  });

}).call(this);
